const HTTP_OK_SUCCESS = 200;
const HTTP_NOT_FOUND = 404;
const HTTP_CREATED = 201;
const HTTP_BAD_REQUEST = 400;
const HTTP_UNPROCESSABLE_ENTITY = 422;

module.exports = {
  HTTP_OK_SUCCESS,
  HTTP_NOT_FOUND,
  HTTP_CREATED,
  HTTP_BAD_REQUEST,
  HTTP_UNPROCESSABLE_ENTITY,
};
